cart/urls.py
from django.urls import path

from .views import (
    shopping_cart_item_add
)
urlpatterns= [
    path('add/<int:cart_item_id>/', shopping_cart_item_add, name='shopping_cart_item_add')
]

eticaret/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from page.views import index
from django.urls import path,include
from django.conf import settings


urlpatterns = [
    path('', index, name='index'),
    path('product/', include('product.urls')),
    path('manage/', include('page.urls')),
    path('cart/', include('cart.urls')),
    path('users/',include('users.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

product/urls.py
from product.views import category_show, ProductDetail
from django.urls.conf import path


urlpatterns = [
    path('<slug:category_slug>', category_show, name='category_show'),
    path('<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
]

product/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User
from page.models import DEFAULT_STATUS, STATUS

# Create your models here.
GENDER_CHOICE = [
            ('men','Erkek'),
            ('women','Kadin'),
            ('unisex','UnİSex'),

]

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(
        max_length=200,
        default=""
    )
    status = models.CharField(
        default=DEFAULT_STATUS,
        choices=STATUS,
        max_length=10
    )
    gender = models.CharField(
        max_length=6,
        default="unisex",
        choices=GENDER_CHOICE,
    )
    createt_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{1000 + self.pk} - {self.gender} - {self.title}"


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(
        max_length=200,
        default="",
    )
    buyer = models.ManyToManyField(User, blank=True)
    content = models.TextField()
    cover_image = models.ImageField(
        upload_to = 'page',
        null = True,
        blank = True,
    )
    price = models.FloatField()
    stock = models.PositiveSmallIntegerField(default=0)
    is_home = models.BooleanField(default=False)
    status = models.CharField(
        default=DEFAULT_STATUS,
        choices=STATUS,
        max_length=10
    )
    # order_field = models.SmallIntegerField(default=0)
    createt_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title



class Comment(models.Model):
    name = models.CharField(max_length=500)
    email = models.EmailField(max_length=150)
    content = models.TextField()
    post = models.ForeignKey(Product, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {}'.format(self.name)

product/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')

product/views.py
from typing import Counter
from page.views import STATUS
from product.models import Category, Product, Comment
from django.shortcuts import get_object_or_404, render
from .forms import CommentForm
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.


def category_show(request, category_slug):
    context = dict()
    context['category'] = get_object_or_404(Category, slug=category_slug)

    # Nav:
    #context['categories'] = Category.objects.filter(
    #    status = STATUS
    #).order_by('title')
    context['items'] = Product.objects.filter(
        category=context['category'],
        status = STATUS,
        stock__gte =1,
    )
    return render(request, 'category_show.html', context)




class ProductDetail(DetailView):
    model = Product
    template_name = 'product_detail.html'

    def product_detail(slug,category_slug):
        context = dict()
        products = Product.objects.filter(
            slug=slug,
            status = STATUS,
                #stockgte ne işe yarıyor tam olarak bilmiyorum, eğer bir hata çıkarsa buradan olabilir. Sonradan kontrol et.
        )
        category= Category.objects.all()
        context['category'] = get_object_or_404(Category, slug=category_slug)

        context = {
        'category': category,
        'products': products,
        }
        return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs['slug']

        form = CommentForm()
        post = get_object_or_404(Product, slug=slug)
        comments = post.comment_set.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form

        return context


    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)

        post = Product.objects.filter(slug = self.kwargs['slug'])[0]
        comments = post.comment_set.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form

        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            content = form.cleaned_data['content']

            comment = Comment.objects.create(
                name=name, email=email, content= content, post=post
            )
            form = CommentForm()
            context['form'] = form
            return self.render_to_response(context=context)

        return self.render_to_response(context=context)

templates/carousel_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}">
</head><!--/head-->

<body>
	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6 ">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href=""><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
								<li><a href=""><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href=""><i class="fa fa-facebook"></i></a></li>
								<li><a href=""><i class="fa fa-twitter"></i></a></li>
								<li><a href=""><i class="fa fa-linkedin"></i></a></li>
								<li><a href=""><i class="fa fa-dribbble"></i></a></li>
								<li><a href=""><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-md-4 clearfix">
						<div class="logo pull-left">
							<a href="index.html"><img src="{% static 'images/home/logo.png' %}" alt="" /></a>
						</div>
						<div class="btn-group pull-right clearfix">
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									USA
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="">Canada</a></li>
									<li><a href="">UK</a></li>
								</ul>
							</div>
							
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									DOLLAR
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="">Canadian Dollar</a></li>
									<li><a href="">Pound</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-md-8 clearfix">
						<div class="shop-menu clearfix pull-right">
							<ul class="nav navbar-nav">
								<li><a href=""><i class="fa fa-user"></i> Account</a></li>
								<li><a href=""><i class="fa fa-star"></i> Wishlist</a></li>
								<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
								<li><a href="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
								<li><a href="login.html"><i class="fa fa-lock"></i> Login</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="index.html">Home</a></li>
								<li class="dropdown"><a href="#" class="active">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="shop.html" class="active">Products</a></li>
										<li><a href="product-details.html">Product Details</a></li> 
										<li><a href="checkout.html">Checkout</a></li> 
										<li><a href="cart.html">Cart</a></li> 
										<li><a href="login.html">Login</a></li> 
                                    </ul>
                                </li> 
								<li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="blog.html">Blog List</a></li>
										<li><a href="blog-single.html">Blog Single</a></li>
                                    </ul>
                                </li> 
								<li><a href="404.html">404</a></li>
								<li><a href="contact-us.html">Contact</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<input type="text" placeholder="Search"/>
						</div>
					</div>
				</div>
				</div>
			</div>
	</header>
	
	<section id="advertisement">
		<div class="container">
			<img src="{% static 'images/shop/advertisement.jpg' %}" alt="" />
		</div>
	</section>
	<div class="container mt-5">
        <div class="row">
            <div class="col-sm-12">
    
                
                <a href="{% url 'page_list' %}" class="btn btn-info">Page - List </a>
    
				<a href="{% url 'carousel_create' %}" class="btn btn-info">Carousel - Create </a>

    
                <hr>
                 
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">PK</th>
                            <th scope="col">Title</th>
                            <th scope="col">Cover Image</th>s
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in carousel %}
                    <tr>
                    <th scope="row">{{ item.pk }}</th>
                    <td>{{ item.title }}</td>
                    <td>
                        {% if item.cover_image %}
                        <img style="width: 100px;height: 100px" src="{{ item.cover_image.url }}" class="w-100">
                        {% else %}
                            Gorsel Yok
                        {% endif %}
                    </td>

						<td><a href="{% url 'carousel_update' item.pk %}" class="btn btn-primary">Edit</a></td>

                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                
               
               
    
            </div>
        </div>
    </div>
    
            
				
	
	<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-shopper</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe1.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe2.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe3.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe4.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="{% static 'images/home/map.png' %}" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="">Online Help</a></li>
								<li><a href="">Contact Us</a></li>
								<li><a href="">Order Status</a></li>
								<li><a href="">Change Location</a></li>
								<li><a href="">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="">T-Shirt</a></li>
								<li><a href="">Mens</a></li>
								<li><a href="">Womens</a></li>
								<li><a href="">Gift Cards</a></li>
								<li><a href="">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="">Terms of Use</a></li>
								<li><a href="">Privecy Policy</a></li>
								<li><a href="">Refund Policy</a></li>
								<li><a href="">Billing System</a></li>
								<li><a href="">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="">Company Information</a></li>
								<li><a href="">Careers</a></li>
								<li><a href="">Store Location</a></li>
								<li><a href="">Affillate Program</a></li>
								<li><a href="">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-Shopper. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->
	

  
    <script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/category_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ category.title }}</h2>
            <div class="row">
                {% for item in items %}
                    {% if item.cover_image %}
                    <div class="col-sm-4" >
                        {% include 'product.html' %}
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/page.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h2>{{ page.title }}</h2>
            {% if page.cover_image %}
            <img style="width:600px;height: 400px" src="{{ page.cover_image.url }}" alt="{{ page.title }}" class="w-100">
            {% endif %}
            <p>
                {{ page.content }}
            </p>
        </div>
    </div>
</div>

{% endblock content %}

templates/product.html
<div class="card mb-3">
    {% if item.cover_image %}
    <img src="{{ item.cover_image.url }}" alt="Card image" style="width: 250px; height: 250px;">
    {% endif %}
      <div class="card-body">
        <p class="card-text">
          <a href="{% url 'product_detail' item.slug %}">
          {{ item.title }}
        </p>
        </a>
      </div>
          
    <div class="card-body">
        <span>
            <span>{{ item.price }} TL</span>
          
								<button type="submit" class="btn btn-outline-success rounded-0" data-toggle="modal"
									data-target="#enrollModal">
									<span>Sepete Ekle</span>
								</button>

        </span>
    </div>
  
</div>
        

templates/product_detail.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ category.title }}</h2>
            <div class="row">
                {% for item in products %}
                    {% if item.cover_image %}
                        {% include 'product.html' %}
                    {% endif %}
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
                            {% if comments %}
                                <div class="row mt-5">
                                    <div class="col-lg-6 offset-lg-3">
                                    Comment{{ comments.count|pluralize }}
                                    <span class="badge badge-dark ml-2">{{ comments.count }}</span>
                                    </div>
                                    {% for comment in comments %}
                                    <div class="col-lg-6 offset-lg-3 mt-2">
                                    <div class="card p-2">
                                        <div class="row">
                                        <div class="col-12">
                                            <img class="rounded-circle mr-2" src="#" alt="">
                                            <strong>{{ comment.name }}</strong> 
                                        </div>
                                        <div class="col-12">
                                            <p class="m-1 mt-3">{{ comment.content }}</p>
                                            <p class="text-right text-muted"><small>{{ comment.created }}</small></p>
                                        </div>
                                        </div>
                                    </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        {% endif %}
                        <!-- Footer-->
                        <div class="row mt-5">
                            <div class="col-lg-6 offset-lg-3">
                              <h3>Leave a comment</h3>
                              <form method='POST'>
                                {% csrf_token %}
                                <div class="form-group">
                                  <span class="ml-2"></span>{{ form.name.label_tag }}
                                  <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" id="id_name"
                                    name="name" value="{{ form.name.value|default:'' }}">
                                </div>
                                <div class="form-group">
                                  <span class="ml-2"></span>
                                  {{ form.email.label_tag }}
                                  <span class="text-muted"><small>(Your email address will not be published)</small></span>
                                  <input type="text" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
                                    name="email" value="{{ form.email.value|default:'' }}">
                                </div>
                                <div class="form-group">
                                  <span class="ml-2"></span>{{ form.content.label_tag }}
                                  <textarea class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
                                    name="content" rows="4">{{ form.content.value|default:'' }}</textarea>
                                </div>
                                <button class="btn btn-primary ml-2" type="submit">Reply</button>
                              </form>
                            </div>
                          </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/register.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'assets/im/post-bg.jpg'%})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Sign Up</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Giriş Yap</p>
                        <div class="my-5">
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form method="POST">{% csrf_token %}
                                <div class="form-floating">
                                    {{form.as_p}}
                                </div>
                                
                                <button type="submit">Kaydol </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        {% endblock content %}
        <!-- Footer-->